# Generated by Django 3.1.1 on 2020-09-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='flavor',
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavors', to='snack_app.snack')),
            ],
        ),
    ]
